{
 "title": "fermento-main",
 "time": { "from": "2026-02-19T15:33:11.610Z", "to": "2026-02-19T18:18:08.317Z" },
 "templating": {
  "list": [
   {
    "name": "feeding_event",
    "label": "Feeding Event",
    "query": "SELECT DISTINCT feeding_event_id\nFROM feeding_samples\nORDER BY feeding_event_id;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Combined",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "fermento",
     "rawSql": "WITH stats AS (\r\n  SELECT\r\n    MIN(temperature) AS min_val,\r\n    MAX(temperature) AS max_val\r\n  FROM feeding_samples\r\n  WHERE feeding_event_id = $feeding_event\r\n)\r\n\r\nSELECT\r\n  timestamp,\r\n  (temperature - stats.min_val) /\r\n  NULLIF(stats.max_val - stats.min_val, 0) AS temperature_norm\r\nFROM feeding_samples, stats\r\nWHERE feeding_event_id = $feeding_event\r\n  AND $__timeFilter(timestamp)\r\nORDER BY timestamp"
    },
    {
     "dataset": "fermento",
     "rawSql": "WITH stats AS (\r\n  SELECT\r\n    MIN(distance) AS min_val,\r\n    MAX(distance) AS max_val\r\n  FROM feeding_samples\r\n  WHERE feeding_event_id = $feeding_event\r\n)\r\n\r\nSELECT\r\n  timestamp,\r\n  (1 - (distance - stats.min_val) /\r\n  NULLIF(stats.max_val - stats.min_val, 0)) AS distance_norm\r\nFROM feeding_samples, stats\r\nWHERE feeding_event_id = $feeding_event\r\n  AND $__timeFilter(timestamp)\r\nORDER BY timestamp"
    },
    {
     "dataset": "fermento",
     "rawSql": "WITH stats AS (\r\n  SELECT\r\n    MIN(humidity) AS min_val,\r\n    MAX(humidity) AS max_val\r\n  FROM feeding_samples\r\n  WHERE feeding_event_id = $feeding_event\r\n)\r\n\r\nSELECT\r\n  timestamp,\r\n  (humidity - stats.min_val) /\r\n  NULLIF(stats.max_val - stats.min_val, 0) AS humidity_norm\r\nFROM feeding_samples, stats\r\nWHERE feeding_event_id = $feeding_event\r\n  AND $__timeFilter(timestamp)\r\nORDER BY timestamp"
    },
    {
     "dataset": "fermento",
     "rawSql": "WITH stats AS (\r\n  SELECT\r\n    MIN(co2) AS min_val,\r\n    MAX(co2) AS max_val\r\n  FROM feeding_samples\r\n  WHERE feeding_event_id = $feeding_event\r\n)\r\n\r\nSELECT\r\n  timestamp,\r\n  (co2 - stats.min_val) /\r\n  NULLIF(stats.max_val - stats.min_val, 0) AS co2_norm\r\nFROM feeding_samples, stats\r\nWHERE feeding_event_id = $feeding_event\r\n  AND $__timeFilter(timestamp)\r\nORDER BY timestamp"
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 0 },
   "options": {
    "content": "<div style=\"width:100%; height:100%; position:relative;\">\r\n     <img id=\"hover_img\" style=\"width:100%; height:100%; object-fit:cover;\" />\r\n     <div id=\"img_label\" style=\"\r\n         width:100%;\r\n         position:absolute;\r\n         bottom:-20%;\r\n         left:50%;\r\n         transform:translateX(-50%);\r\n         background:rgba(0,0,0,0.5);\r\n         color:white;\r\n         padding:4px 10px;\r\n         border-radius:6px;\r\n         font-size:14px;\r\n         text-align:center\r\n       \">\r\n          image_name.jpg\r\n     </div>\r\n</div>"
   },
   "targets": [
    {
     "dataset": "fermento",
     "rawSql": "SELECT * FROM feeding_samples WHERE feeding_event_id = $feeding_event "
    }
   ]
  },
  {
   "title": "Feeding",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "dataset": "fermento",
     "rawSql": "SELECT\r\n  fe.id,\r\n  fe.timestamp,\r\n  s.name AS starter_name,\r\n  j.name AS jar_name,\r\n  fe.starter_ratio,\r\n  fe.water_ratio,\r\n  fe.flour_ratio\r\nFROM feeding_events fe\r\nJOIN starters s\r\n  ON fe.starter_id = s.id\r\nJOIN jars j\r\n  ON fe.jar_id = j.id\r\nWHERE fe.id = $feeding_event;\r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "fermento",
     "rawSql": "SELECT temperature, \"timestamp\" FROM feeding_samples WHERE feeding_event_id = $feeding_event "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "dataset": "fermento",
     "rawSql": "SELECT humidity, \"timestamp\" FROM feeding_samples WHERE feeding_event_id = $feeding_event "
    }
   ]
  },
  {
   "title": "Distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "fermento",
     "rawSql": "SELECT distance, \"timestamp\" FROM feeding_samples WHERE feeding_event_id = $feeding_event "
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "dataset": "fermento",
     "rawSql": "SELECT co2, \"timestamp\" FROM feeding_samples WHERE feeding_event_id = $feeding_event "
    }
   ]
  }
 ]
}