"""
analysis.py — Dataset analysis and visualization.

Generates a 7-panel dashboard showing temperature distribution, LOOCV error
patterns, stage durations, coverage gaps, and signal characteristics across
all runs. Designed to highlight where additional data would most improve
model performance.

Usage:
    python main.py analyze <data_dir> [--loocv-json <path>] [--output <path>]

The optional --loocv-json flag points to a JSON file with per-run LOOCV
results (generated by validate). Without it, only dataset-level panels
are plotted and error panels are skipped.
"""

import json
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from pathlib import Path

from config import STAGE_NAMES
from lib.data import load_all_runs


# ---------------------------------------------------------------------------
# Style constants
# ---------------------------------------------------------------------------

BG      = "#0f1117"
PANEL   = "#181c27"
GRID    = "#252a38"
DIMTXT  = "#5a5f72"
TXT     = "#9ca0af"
BRIGHT  = "#d4d8e4"
WHITE   = "#eceff8"

STAGE_C = {"Lag": "#6baed6", "Exponential": "#74c476", "Peak": "#fdd835", "Decline": "#ef6c57"}
GREEN   = "#22c55e"
AMBER   = "#f59e0b"
RED     = "#ef4444"
CYAN    = "#38bdf8"

BAND_DEFS = [
    ("22–25", 22, 25, "#60a5fa"),
    ("25–28", 25, 28, "#34d399"),
    ("28–31", 28, 31, "#fbbf24"),
    ("31–34", 31, 34, "#fb923c"),
    ("34–36", 34, 36, "#f87171"),
]


def _apply_style():
    """Apply the dark theme to matplotlib rcParams."""
    plt.rcParams.update({
        "figure.facecolor": BG,
        "axes.facecolor": PANEL,
        "axes.edgecolor": GRID,
        "axes.labelcolor": TXT,
        "xtick.color": DIMTXT,
        "ytick.color": DIMTXT,
        "text.color": BRIGHT,
        "grid.color": GRID,
        "grid.linewidth": 0.4,
        "font.family": "sans-serif",
        "font.size": 9,
    })


# ---------------------------------------------------------------------------
# Data extraction
# ---------------------------------------------------------------------------

def _build_run_profiles(raw_df: pd.DataFrame) -> pd.DataFrame:
    """Extract per-run statistics from the raw loaded DataFrame."""
    profiles = []

    for run_id, group in raw_df.groupby("run_id"):
        group = group.sort_values("timestamp").reset_index(drop=True)
        elapsed = (group["timestamp"] - group["timestamp"].iloc[0]).dt.total_seconds() / 60
        dist = group["distance"]
        rise = dist.iloc[0] - dist

        stage_durs = {}
        stage_starts = {}
        for s in range(4):
            mask = group["stage"] == s
            if mask.any():
                start = elapsed[mask].iloc[0]
                end = elapsed[mask].iloc[-1]
                stage_durs[s] = end - start
                stage_starts[s] = start

        # 90% plateau width
        threshold_90 = rise.max() * 0.90
        above_90 = rise >= threshold_90
        if above_90.any():
            plateau_90 = elapsed[above_90].iloc[-1] - elapsed[above_90].iloc[0]
        else:
            plateau_90 = 0.0

        profiles.append({
            "run": str(run_id),
            "temp": group["temperature"].mean(),
            "temp_std": group["temperature"].std(),
            "duration": elapsed.iloc[-1],
            "samples": len(group),
            "total_rise": rise.max(),
            "co2_max": group["co2"].max(),
            "plateau_90": plateau_90,
            "lag_dur": stage_durs.get(0, 0),
            "exp_dur": stage_durs.get(1, 0),
            "peak_dur": stage_durs.get(2, 0),
            "dec_dur": stage_durs.get(3, 0),
            "lag_start": stage_starts.get(0, 0),
            "exp_start": stage_starts.get(1, 0),
            "peak_start": stage_starts.get(2, 0),
            "dec_start": stage_starts.get(3, 0),
        })

    return pd.DataFrame(profiles).sort_values("temp").reset_index(drop=True)


def _merge_loocv(profiles: pd.DataFrame, loocv: dict) -> pd.DataFrame:
    """Merge LOOCV results dict into the profiles DataFrame."""
    loocv_rows = []
    for run_id, data in loocv.items():
        loocv_rows.append({
            "run": str(run_id),
            "mae": data.get("mae", 0),
            "worst": data.get("worst", 0),
            "exp_err": data.get("exp_err", 0),
            "peak_err": data.get("peak_err", 0),
            "dec_err": data.get("dec_err", 0),
        })
    ldf = pd.DataFrame(loocv_rows)
    return profiles.merge(ldf, on="run", how="left")


# ---------------------------------------------------------------------------
# Plot panels
# ---------------------------------------------------------------------------

def _plot_temp_histogram(ax, df):
    """Panel 1: Temperature distribution with gap highlighting."""
    bins = np.arange(22, 36.5, 1)
    n, bin_edges, patches = ax.hist(df["temp"], bins=bins, edgecolor=PANEL, linewidth=1.2, alpha=0.9)
    for patch, left_edge in zip(patches, bin_edges[:-1]):
        if left_edge < 25:   patch.set_facecolor("#60a5fa")
        elif left_edge < 28: patch.set_facecolor("#34d399")
        elif left_edge < 31: patch.set_facecolor("#fbbf24")
        elif left_edge < 34: patch.set_facecolor("#fb923c")
        else:                patch.set_facecolor("#f87171")

    # Highlight thin bands
    for label, lo, hi, _ in BAND_DEFS:
        count = ((df["temp"] >= lo) & (df["temp"] < hi)).sum()
        if count <= 1:
            ax.axvspan(lo, hi, alpha=0.08, color=RED, zorder=0)
            ax.annotate(
                f"THIN COVERAGE\n{count} run{'s' if count != 1 else ''} only",
                xy=((lo + hi) / 2, max(n) * 0.75), fontsize=8,
                color=RED, ha="center", fontweight="bold",
                bbox=dict(boxstyle="round,pad=0.3", fc=BG, ec=RED, alpha=0.8),
            )

    ax.set_xlabel("Mean Temperature (°C)")
    ax.set_ylabel("Number of Runs")
    ax.set_title("Temperature Distribution", fontsize=12, fontweight="bold", color=WHITE, pad=10)
    ax.grid(axis="y", alpha=0.3)
    ax.set_xlim(21.5, 36)


def _plot_mae_vs_temp(ax, df):
    """Panel 2: MAE vs temperature scatter."""
    colors = [RED if m > 30 else AMBER if m > 15 else GREEN for m in df["mae"]]
    sizes = [max(40, min(300, m * 3)) for m in df["mae"]]

    ax.scatter(df["temp"], df["mae"], c=colors, s=sizes, alpha=0.85,
               edgecolors=PANEL, linewidth=1, zorder=3)

    for _, r in df.iterrows():
        if r["mae"] > 20:
            ax.annotate(f'Run {r["run"]}', (r["temp"], r["mae"]),
                        textcoords="offset points", xytext=(8, 5),
                        fontsize=7.5, color=RED, fontweight="bold")
        elif r["mae"] < 6:
            ax.annotate(f'Run {r["run"]}', (r["temp"], r["mae"]),
                        textcoords="offset points", xytext=(8, -2),
                        fontsize=7, color=GREEN, alpha=0.8)

    ax.axhline(15, color=AMBER, linewidth=0.8, linestyle="--", alpha=0.5)
    ax.text(ax.get_xlim()[1] - 0.2, 15.5, "15 min", fontsize=7, color=AMBER, ha="right")
    ax.axhline(30, color=RED, linewidth=0.8, linestyle="--", alpha=0.5)
    ax.text(ax.get_xlim()[1] - 0.2, 31, "30 min", fontsize=7, color=RED, ha="right")

    ax.set_xlabel("Mean Temperature (°C)")
    ax.set_ylabel("MAE (min)")
    ax.set_title("LOOCV Error vs Temperature", fontsize=12, fontweight="bold", color=WHITE, pad=10)
    ax.grid(alpha=0.3)


def _plot_stage_durations(ax, df):
    """Panel 3: Stacked stage duration bars sorted by temperature."""
    bar_width = 0.7
    x = np.arange(len(df))
    bottoms = np.zeros(len(df))

    for stage, key in [("Lag", "lag_dur"), ("Exponential", "exp_dur"),
                        ("Peak", "peak_dur"), ("Decline", "dec_dur")]:
        vals = df[key].values
        ax.bar(x, vals, bar_width, bottom=bottoms, label=stage,
               color=STAGE_C[stage], edgecolor=PANEL, linewidth=0.5, alpha=0.88)
        bottoms += vals

    for i, r in df.iterrows():
        ax.text(i, r["duration"] + 12, f'{r["temp"]:.1f}°', ha="center", fontsize=7, color=DIMTXT)

    ax.set_xticks(x)
    ax.set_xticklabels([f'Run {r}' for r in df["run"]], rotation=45, ha="right", fontsize=8)
    ax.set_ylabel("Duration (min)")
    ax.set_title("Stage Durations by Run (sorted by temperature, coldest → hottest)",
                 fontsize=12, fontweight="bold", color=WHITE, pad=10)
    ax.legend(loc="upper right", fontsize=8, framealpha=0.3, edgecolor=GRID,
              facecolor=BG, labelcolor=BRIGHT)
    ax.grid(axis="y", alpha=0.3)


def _plot_per_stage_errors(ax, df):
    """Panel 4: Per-stage absolute transition errors."""
    bar_w = 0.25
    x = np.arange(len(df))

    for i, (key, label, color) in enumerate([
        ("exp_err", "Exponential", STAGE_C["Exponential"]),
        ("peak_err", "Peak", STAGE_C["Peak"]),
        ("dec_err", "Decline", STAGE_C["Decline"]),
    ]):
        vals = df[key].abs().values
        ax.bar(x + i * bar_w, vals, bar_w, label=label, color=color,
               alpha=0.8, edgecolor=PANEL, linewidth=0.5)

    ax.set_xticks(x + bar_w)
    ax.set_xticklabels([f'{r}' for r in df["run"]], rotation=45, ha="right", fontsize=7.5)
    ax.set_ylabel("|Error| (min)")
    ax.set_xlabel("Run")
    ax.set_title("Transition Error by Stage", fontsize=12, fontweight="bold", color=WHITE, pad=10)
    ax.legend(fontsize=8, framealpha=0.3, edgecolor=GRID, facecolor=BG, labelcolor=BRIGHT)
    ax.grid(axis="y", alpha=0.3)

    # Cap y-axis for readability, annotate clipped bars
    y_cap = 100
    ax.set_ylim(0, y_cap)
    for _, r in df.iterrows():
        for key in ["exp_err", "peak_err", "dec_err"]:
            if abs(r[key]) > y_cap * 0.95:
                idx = df.index.get_loc(r.name)
                offset = {"exp_err": 0, "peak_err": 1, "dec_err": 2}[key]
                ax.annotate(f"{abs(r[key]):.0f}", (idx + offset * bar_w, y_cap * 0.97),
                            fontsize=7, color=RED, ha="center", fontweight="bold")


def _plot_coverage_vs_mae(ax, df):
    """Panel 5: Run count and avg MAE per temperature band."""
    band_stats = []
    for label, lo, hi, color in BAND_DEFS:
        mask = (df["temp"] >= lo) & (df["temp"] < hi)
        sub = df[mask]
        band_stats.append({
            "label": label,
            "count": len(sub),
            "avg_mae": sub["mae"].mean() if len(sub) else 0,
            "color": color,
        })

    bdf = pd.DataFrame(band_stats)
    x = np.arange(len(bdf))

    ax.bar(x - 0.2, bdf["count"], 0.35,
           color=[b["color"] for b in band_stats],
           alpha=0.85, edgecolor=PANEL, linewidth=0.8, label="# Runs")

    ax2 = ax.twinx()
    ax2.bar(x + 0.2, bdf["avg_mae"], 0.35,
            color=[b["color"] for b in band_stats],
            alpha=0.4, edgecolor=[b["color"] for b in band_stats],
            linewidth=1.5, linestyle="--", label="Avg MAE")

    ax.set_xticks(x)
    ax.set_xticklabels(bdf["label"], fontsize=9)
    ax.set_ylabel("Number of Runs", color=BRIGHT)
    ax2.set_ylabel("Avg MAE (min)", color=DIMTXT)
    ax2.tick_params(colors=DIMTXT)
    ax.set_title("Coverage vs Error by Temperature Band",
                 fontsize=12, fontweight="bold", color=WHITE, pad=10)
    ax.grid(axis="y", alpha=0.2)

    lines1, labels1 = ax.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax.legend(lines1 + lines2, labels1 + labels2, fontsize=8, framealpha=0.3,
              edgecolor=GRID, facecolor=BG, labelcolor=BRIGHT, loc="upper right")


def _plot_temp_vs_duration(ax, df):
    """Panel 6: Temperature vs duration scatter with trend lines."""
    ax.scatter(df["temp"], df["duration"], s=60, color=CYAN, alpha=0.8,
               label="Total duration", zorder=3, edgecolors=PANEL)
    ax.scatter(df["temp"], df["exp_dur"], s=40, color=STAGE_C["Exponential"],
               alpha=0.8, label="Exp duration", zorder=3, edgecolors=PANEL)
    ax.scatter(df["temp"], df["peak_dur"], s=40, color=STAGE_C["Peak"],
               alpha=0.8, label="Peak duration", zorder=3, edgecolors=PANEL)

    t_smooth = np.linspace(df["temp"].min(), df["temp"].max(), 100)
    for vals, c in [(df["duration"], CYAN),
                    (df["exp_dur"], STAGE_C["Exponential"]),
                    (df["peak_dur"], STAGE_C["Peak"])]:
        z = np.polyfit(df["temp"], vals, 2)
        ax.plot(t_smooth, np.poly1d(z)(t_smooth), color=c, alpha=0.3,
                linewidth=1.5, linestyle="--")

    # Annotate the coldest run if it's a clear outlier
    coldest = df.iloc[0]
    if coldest["duration"] > df["duration"].median() * 1.5:
        ax.annotate(
            f'Run {coldest["run"]}\n{coldest["duration"]:.0f} min total\n'
            f'{coldest["exp_dur"]:.0f} min Exp\n{coldest["peak_dur"]:.0f} min Peak',
            (coldest["temp"], coldest["duration"]),
            textcoords="offset points", xytext=(15, -10),
            fontsize=7, color=RED, fontweight="bold",
            arrowprops=dict(arrowstyle="->", color=RED, lw=0.8),
            bbox=dict(boxstyle="round,pad=0.3", fc=BG, ec=RED, alpha=0.8),
        )

    ax.set_xlabel("Mean Temperature (°C)")
    ax.set_ylabel("Duration (min)")
    ax.set_title("Temperature vs Duration (non-linear relationship)",
                 fontsize=12, fontweight="bold", color=WHITE, pad=10)
    ax.legend(fontsize=8, framealpha=0.3, edgecolor=GRID, facecolor=BG, labelcolor=BRIGHT)
    ax.grid(alpha=0.3)


def _plot_co2_vs_temp(ax, df, has_loocv: bool):
    """Panel 7: Max CO₂ vs temperature, colored by MAE if available."""
    from matplotlib.lines import Line2D

    if has_loocv:
        colors = [RED if r["mae"] > 30 else AMBER if r["mae"] > 15 else GREEN
                  for _, r in df.iterrows()]
    else:
        colors = [CYAN] * len(df)

    ax.scatter(df["temp"], df["co2_max"] / 1000, s=70, c=colors, alpha=0.85,
               edgecolors=PANEL, linewidth=1, zorder=3)

    for _, r in df.iterrows():
        if r["co2_max"] < 20000 or r["co2_max"] > 43000:
            ax.annotate(f'Run {r["run"]}', (r["temp"], r["co2_max"] / 1000),
                        textcoords="offset points", xytext=(8, 3),
                        fontsize=7, color=DIMTXT)

    ax.axhspan(0, 20, alpha=0.05, color=RED, zorder=0)
    ax.text(ax.get_xlim()[1] - 0.3, 18.5, "Low CO₂ zone\n(under-represented)",
            fontsize=7.5, color=RED, ha="right", alpha=0.7)

    ax.set_xlabel("Mean Temperature (°C)")
    ax.set_ylabel("Max CO₂ (×1000 ppm)")

    if has_loocv:
        ax.set_title("Max CO₂ vs Temperature (color = MAE severity)",
                     fontsize=12, fontweight="bold", color=WHITE, pad=10)
        legend_elements = [
            Line2D([0], [0], marker='o', color='none', markerfacecolor=GREEN, markersize=8, label='MAE ≤ 15'),
            Line2D([0], [0], marker='o', color='none', markerfacecolor=AMBER, markersize=8, label='15 < MAE ≤ 30'),
            Line2D([0], [0], marker='o', color='none', markerfacecolor=RED, markersize=8, label='MAE > 30'),
        ]
        ax.legend(handles=legend_elements, fontsize=8, framealpha=0.3,
                  edgecolor=GRID, facecolor=BG, labelcolor=BRIGHT)
    else:
        ax.set_title("Max CO₂ vs Temperature",
                     fontsize=12, fontweight="bold", color=WHITE, pad=10)

    ax.grid(alpha=0.3)


# ---------------------------------------------------------------------------
# Console summary
# ---------------------------------------------------------------------------

def _print_summary(df: pd.DataFrame, has_loocv: bool) -> None:
    """Print a concise text summary of dataset characteristics."""
    n_runs = len(df)
    n_samples = df["samples"].sum()
    print(f"\nDataset: {n_runs} runs, {n_samples:,.0f} samples")
    print(f"Temperature range: {df['temp'].min():.1f}–{df['temp'].max():.1f}°C\n")

    print("Temperature coverage:")
    for label, lo, hi, _ in BAND_DEFS:
        mask = (df["temp"] >= lo) & (df["temp"] < hi)
        count = mask.sum()
        runs = df[mask]["run"].tolist()
        bar = "█" * count + "░" * (6 - min(count, 6))
        status = "← NEEDS DATA" if count <= 1 else ""
        print(f"  {label}°C  {bar}  {count} runs  ({', '.join(runs)})  {status}")

    print(f"\nStage duration ranges (min):")
    for stage, key in [("Lag", "lag_dur"), ("Exponential", "exp_dur"),
                        ("Peak", "peak_dur"), ("Decline", "dec_dur")]:
        vals = df[key]
        print(f"  {stage:12s}  {vals.min():5.0f} – {vals.max():5.0f}  (mean {vals.mean():.0f})")

    print(f"\nCorrelation (temp vs timing):")
    for col, label in [("exp_start", "Exp start"), ("peak_start", "Peak start"),
                        ("dec_start", "Dec start"), ("duration", "Total duration")]:
        corr = df["temp"].corr(df[col])
        print(f"  temp vs {label:15s}  r = {corr:+.3f}")

    if has_loocv:
        print(f"\nLOOCV error by temperature band:")
        for label, lo, hi, _ in BAND_DEFS:
            mask = (df["temp"] >= lo) & (df["temp"] < hi)
            sub = df[mask]
            if len(sub):
                print(f"  {label}°C  ({len(sub)} runs)  "
                      f"mean MAE={sub['mae'].mean():.1f}  "
                      f"worst MAE={sub['mae'].max():.1f}  "
                      f"max single err={sub['worst'].max():.1f}")


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def analyze(
    data_dir: str,
    loocv_json: str = None,
    output: str = None,
) -> None:
    """
    Analyze the dataset and generate the 7-panel dashboard.

    Args:
        data_dir:   Path to directory of labeled CSV run files.
        loocv_json: Optional path to JSON with per-run LOOCV results.
                    Expected format: {"run_id": {"mae": ..., "worst": ...,
                    "exp_err": ..., "peak_err": ..., "dec_err": ...}, ...}
        output:     Output path for the PNG. Defaults to <data_dir>/analysis.png.
    """
    print(f"Loading runs from: {data_dir}")
    raw_df = load_all_runs(data_dir)
    n_runs = raw_df["run_id"].nunique()
    print(f"  {n_runs} runs, {len(raw_df):,} samples")

    profiles = _build_run_profiles(raw_df)

    # Load LOOCV results if provided
    has_loocv = False
    if loocv_json:
        loocv_path = Path(loocv_json)
        if loocv_path.exists():
            with open(loocv_path) as f:
                loocv = json.load(f)
            profiles = _merge_loocv(profiles, loocv)
            has_loocv = True
            print(f"  LOOCV results loaded from {loocv_json}")
        else:
            print(f"  Warning: LOOCV file not found: {loocv_json}")

    # Fill missing LOOCV columns with zeros for plotting
    for col in ["mae", "worst", "exp_err", "peak_err", "dec_err"]:
        if col not in profiles.columns:
            profiles[col] = 0.0

    _print_summary(profiles, has_loocv)

    # --- Generate dashboard ---
    _apply_style()

    if has_loocv:
        fig = plt.figure(figsize=(20, 24))
        gs = gridspec.GridSpec(4, 2, figure=fig,
            hspace=0.35, wspace=0.25,
            left=0.07, right=0.95, top=0.95, bottom=0.04)
    else:
        # Without LOOCV: skip error panels (2, 4, 5), show 4 panels
        fig = plt.figure(figsize=(20, 14))
        gs = gridspec.GridSpec(2, 2, figure=fig,
            hspace=0.35, wspace=0.25,
            left=0.07, right=0.95, top=0.93, bottom=0.06)

    fig.patch.set_facecolor(BG)
    fig.suptitle("Fermento — Dataset Analysis & Model Gaps",
                 fontsize=20, fontweight="bold", color=WHITE, y=0.975)

    if has_loocv:
        _plot_temp_histogram(fig.add_subplot(gs[0, 0]), profiles)
        _plot_mae_vs_temp(fig.add_subplot(gs[0, 1]), profiles)
        _plot_stage_durations(fig.add_subplot(gs[1, :]), profiles)
        _plot_per_stage_errors(fig.add_subplot(gs[2, 0]), profiles)
        _plot_coverage_vs_mae(fig.add_subplot(gs[2, 1]), profiles)
        _plot_temp_vs_duration(fig.add_subplot(gs[3, 0]), profiles)
        _plot_co2_vs_temp(fig.add_subplot(gs[3, 1]), profiles, has_loocv)
    else:
        _plot_temp_histogram(fig.add_subplot(gs[0, 0]), profiles)
        _plot_stage_durations(fig.add_subplot(gs[0, 1]), profiles)
        _plot_temp_vs_duration(fig.add_subplot(gs[1, 0]), profiles)
        _plot_co2_vs_temp(fig.add_subplot(gs[1, 1]), profiles, has_loocv)

    out_path = Path(output) if output else Path(data_dir) / "analysis.png"
    plt.savefig(out_path, dpi=150, bbox_inches="tight", facecolor=BG)
    plt.close()
    print(f"\n✓ Dashboard saved → {out_path}")
