FROM python:3.12-slim

WORKDIR /src
COPY ./requirements.txt ./requirements.txt
COPY ./src ./

RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8091"]